name: Azure App Service Publish Profile
author: Aliencube Community
description: Retrieve or reset the publish profile of Azure Web App or Functions App in XML format

branding:
  icon: clipboard
  color: purple

inputs:
  resourceGroupName:
    description: Resource group name.
    required: true
  appName:
    description: App instance name.
    required: true
  reset:
    description: Value indicating whether to reset the publish profile or not.
    required: false
    default: 'false'
  subscriptionId:
    description: Optionally provide the Azure Subscription Id to select the appropriate Azure Subscription where the App instance resides.
    required: false
    default: ''

outputs:
  profile:
    description: Publish profile in XML.

runs:
  using: docker
  image: Dockerfile
  args:
  - -ResourceGroupName
  - ${{ inputs.resourceGroupName }}
  - -AppName
  - ${{ inputs.appName }}
  - -Reset
  - ${{ inputs.reset }}
  - -SubscriptionId
  - ${{ inputs.subscriptionId }}
