name: Azure App Service Publish Profile
author: Aliencube Community
description: Retrieve the publish profile of Azure Web App or Functions App in XML format

branding:
  icon: clipboard
  color: purple

inputs:
  resourceGroupName:
    description: Resource group name.
    required: true
  appName:
    description: App instance name.
    required: true

outputs:
  profile:
    description: Publish profile in XML.

runs:
  using: docker
  image: Dockerfile
  args:
  - -ResourceGroupName
  - ${{ inputs.resourceGroupName }}
  - -AppName
  - ${{ inputs.appName }}
